version: 1.2
notebooks:
  - format: JUPYTER
    path: /LORIS/preprocessing_data.ipynb
    name: Preprocessing LORIS
    topic: LORIS raw data preprocessing from Chang et al. 2024 article.
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org

  - format: JUPYTER
    path: /LORIS/posprocessing.ipynb
    name: Postprocessing LORIS
    topic: LORIS model evaluation comparing model metrics from Chang et al. (2024) with Galaxy-ML model metrics.
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org

workflows:
  - subclass: GALAXY
    primaryDescriptorPath: /LORIS/galaxy_workflow/Galaxy-ML2-LORIS_model.ga
    topic: LORIS model (Chang et al., 2024) Reproducibility using Galaxy-ML tools
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org
